# Generated by Django 4.0.6 on 2022-07-12 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('age', models.CharField(choices=[('LESS THEN 30', 'LESS THEN 30'), ('BETWEEN 31 TO 35', 'BETWEEN 31 TO 35'), ('BETWEEN 36 TO 40', 'BETWEEN 36 TO 40'), ('ABOVE 40', 'ABOVE 40')], max_length=50)),
                ('clinic_name', models.CharField(max_length=150)),
                ('education', models.CharField(max_length=150)),
                ('specialty', models.CharField(max_length=150)),
            ],
        ),
    ]
