# Generated by Django 4.0.6 on 2022-07-16 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advising',
            fields=[
                ('id', models.IntegerField()),
                ('ip', models.CharField(max_length=32)),
                ('created_at', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=64)),
                ('time', models.CharField(max_length=5)),
                ('seen', models.IntegerField(blank=True, null=True)),
                ('done', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'advising',
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.IntegerField()),
                ('created_at', models.BigIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('name_clean', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.IntegerField()),
                ('post_id', models.IntegerField()),
                ('comment_author', models.CharField(max_length=127)),
                ('comment_author_email', models.CharField(max_length=64)),
                ('comment_author_ip', models.CharField(max_length=16)),
                ('comment_date', models.BigIntegerField()),
                ('comment_content', models.TextField()),
                ('commpent_approved', models.IntegerField()),
                ('commeent_agent', models.TextField()),
                ('comment_parent_id', models.IntegerField(blank=True, null=True)),
                ('user_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'comments',
            },
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.IntegerField()),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('national_code', models.CharField(max_length=10)),
                ('mobile', models.CharField(max_length=16)),
                ('phone', models.CharField(max_length=16)),
                ('email', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('location_name', models.CharField(max_length=255)),
                ('location_type', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'customers',
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
            },
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.IntegerField()),
                ('name', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=255, null=True)),
                ('type', models.CharField(max_length=255)),
                ('time', models.IntegerField()),
            ],
            options={
                'db_table': 'files',
            },
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.IntegerField()),
                ('item_name', models.CharField(max_length=255)),
                ('item_description', models.TextField()),
                ('item_price', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'items',
            },
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.IntegerField()),
                ('name', models.CharField(max_length=128)),
                ('email', models.CharField(max_length=64)),
                ('mobile', models.CharField(max_length=12)),
                ('title', models.CharField(max_length=255)),
                ('messages', models.TextField()),
                ('visitor_ip', models.CharField(max_length=32)),
                ('message_time', models.IntegerField()),
                ('seen', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'messages',
            },
        ),
        migrations.CreateModel(
            name='Newsletters',
            fields=[
                ('id', models.IntegerField()),
                ('email', models.CharField(max_length=255)),
                ('register_time', models.IntegerField()),
                ('user_ip', models.CharField(max_length=64)),
                ('seen', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'newsletters',
            },
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.IntegerField()),
                ('user_id', models.CharField(blank=True, max_length=255, null=True)),
                ('category_id', models.IntegerField(blank=True, null=True)),
                ('media_name', models.CharField(max_length=255)),
                ('media_description', models.CharField(max_length=255)),
                ('post_date', models.BigIntegerField()),
                ('post_title_fa', models.TextField()),
                ('post_content_fa', models.TextField()),
                ('post_status', models.CharField(max_length=16)),
                ('comment_status', models.CharField(max_length=16)),
                ('post_name', models.CharField(max_length=128)),
                ('comment_count', models.IntegerField()),
                ('post_modified', models.BigIntegerField()),
                ('post_visit', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'posts',
            },
        ),
        migrations.CreateModel(
            name='PostTags',
            fields=[
                ('id', models.IntegerField()),
                ('post_id', models.IntegerField()),
                ('tag_id', models.IntegerField()),
            ],
            options={
                'db_table': 'post_tags',
            },
        ),
        migrations.CreateModel(
            name='Secretaries',
            fields=[
                ('id', models.IntegerField()),
                ('name', models.CharField(max_length=128)),
                ('mobile', models.CharField(max_length=13)),
                ('clinic_name', models.CharField(max_length=255)),
                ('clinic_phone', models.CharField(max_length=32)),
                ('clinic_address', models.TextField()),
                ('friend_mobile', models.CharField(blank=True, max_length=13, null=True)),
                ('ip', models.CharField(max_length=32)),
                ('created_at', models.IntegerField()),
                ('seen', models.IntegerField()),
            ],
            options={
                'db_table': 'secretaries',
            },
        ),
        migrations.CreateModel(
            name='SurverySurvey',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=50)),
                ('clinic_name', models.CharField(max_length=150)),
                ('education', models.CharField(max_length=150)),
                ('specialty', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'survery_survey',
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'unique_together': {('app_label', 'model')},
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='weblog.djangocontenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='weblog.authuser')),
            ],
            options={
                'db_table': 'django_admin_log',
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='weblog.djangocontenttype')),
            ],
            options={
                'db_table': 'auth_permission',
                'unique_together': {('content_type', 'codename')},
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='weblog.authpermission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='weblog.authuser')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'unique_together': {('user', 'permission')},
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='weblog.authgroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='weblog.authuser')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'unique_together': {('user', 'group')},
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='weblog.authgroup')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='weblog.authpermission')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'unique_together': {('group', 'permission')},
            },
        ),
    ]
