# Generated by Django 4.0.6 on 2022-08-11 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('weblog', '0002_delete_advising_delete_authgroup_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=255, null=True)),
                ('category_id', models.IntegerField(blank=True, null=True)),
                ('media_name', models.CharField(max_length=255)),
                ('media_description', models.CharField(max_length=255)),
                ('post_date', models.BigIntegerField()),
                ('post_title_fa', models.TextField()),
                ('post_content_fa', models.TextField()),
                ('post_status', models.CharField(max_length=16)),
                ('comment_status', models.CharField(max_length=16)),
                ('post_name', models.CharField(max_length=128)),
                ('comment_count', models.IntegerField()),
                ('post_modified', models.BigIntegerField()),
                ('post_visit', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'posts',
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=127)),
                ('author_email', models.CharField(max_length=64)),
                ('comment_date', models.DateField(default=None)),
                ('comment_content', models.TextField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='weblog.posts')),
            ],
            options={
                'db_table': 'comments',
            },
        ),
    ]
