# Generated by Django 4.0.6 on 2022-08-14 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='post_Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=127)),
                ('author_email', models.CharField(max_length=64)),
                ('comment_date', models.DateField(auto_now_add=True)),
                ('comment_content', models.TextField()),
                ('status', models.CharField(choices=[('approved', 'approved'), ('disapproved', 'disapproved')], default='disapproved', max_length=20)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='weblog.posts')),
            ],
            options={
                'db_table': 'post_Comments',
                'ordering': ['-comment_date'],
            },
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
