# Generated by Django 4.0.6 on 2022-08-11 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0004_alter_comments_comment_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=255, null=True)),
                ('type', models.CharField(max_length=255)),
                ('time', models.IntegerField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='img', to='weblog.posts')),
            ],
            options={
                'db_table': 'files',
            },
        ),
    ]
