# Generated by Django 4.0.6 on 2022-09-06 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0007_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitors',
            name='visit_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
