# Generated by Django 4.0.6 on 2022-09-07 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0008_alter_visitors_visit_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('register_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'newsletters',
            },
        ),
    ]
