# Generated by Django 4.0.6 on 2022-07-19 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support',
            name='phone_number',
            field=models.IntegerField(blank=True),
        ),
    ]
