# Generated by Django 4.0.6 on 2022-07-19 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_alter_support_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='support',
            name='phone_number',
        ),
    ]
