# Generated by Django 4.0.6 on 2022-07-19 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_remove_support_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='support',
            name='phone_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='support',
            name='support_time',
            field=models.CharField(choices=[('بین ساعت 15 تا 16', 'بین ساعت 15 تا 16'), ('بین ساعت 16 تا 17', 'بین ساعت 16 تا 17'), ('بین ساعت 18 تا 20', 'بین ساعت 18 تا 20')], max_length=100),
        ),
    ]
