# Generated by Django 4.0.6 on 2022-07-17 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contact_us',
            table=None,
        ),
    ]
